/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        hf: {
          'bg-primary': 'var(--hf-bg-primary)',
          'bg-secondary': 'var(--hf-bg-secondary)',
          'bg-tertiary': 'var(--hf-bg-tertiary)',
          'text-primary': 'var(--hf-text-primary)',
          'text-secondary': 'var(--hf-text-secondary)',
          'text-tertiary': 'var(--hf-text-tertiary)',
          border: 'var(--hf-border)',
          accent: 'var(--hf-accent)',
          'accent-hover': 'var(--hf-accent-hover)',
          card: 'var(--hf-card)',
          shadow: 'var(--hf-shadow)',
          success: '#22C55E',
          warning: '#F59E0B',
          danger: '#EF4444',
          anti: '#10B981',
          premium: '#A855F7',
          'chart-pink': '#EC4899',
          'chart-teal': '#06B6D4',
        },
      },
      fontSize: {
        'hf-display-lg': ['36px', { lineHeight: '1.1', fontWeight: '800' }],
        'hf-display-md': ['28px', { lineHeight: '1.15', fontWeight: '800' }],
        'hf-headline-lg': ['26px', { lineHeight: '1.2', fontWeight: '800' }],
        'hf-headline-md': ['22px', { lineHeight: '1.2', fontWeight: '700' }],
        'hf-headline-sm': ['18px', { lineHeight: '1.25', fontWeight: '700' }],
        'hf-title-lg': ['17px', { lineHeight: '1.3', fontWeight: '700' }],
        'hf-title-md': ['15px', { lineHeight: '1.3', fontWeight: '600' }],
        'hf-title-sm': ['13px', { lineHeight: '1.3', fontWeight: '600' }],
        'hf-body-lg': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'hf-body-md': ['14px', { lineHeight: '1.45', fontWeight: '400' }],
        'hf-body-sm': ['13px', { lineHeight: '1.4', fontWeight: '400' }],
        'hf-label-lg': ['14px', { lineHeight: '1.2', fontWeight: '600' }],
        'hf-label-md': ['12px', { lineHeight: '1.2', fontWeight: '600' }],
        'hf-label-sm': ['11px', { lineHeight: '1.2', fontWeight: '500' }],
      },
      borderRadius: {
        'hf-sm': '8px',
        'hf-md': '12px',
        'hf-lg': '16px',
        'hf-xl': '24px',
        'hf-full': '999px',
      },
      spacing: {
        'hf-4': '4px',
        'hf-8': '8px',
        'hf-12': '12px',
        'hf-16': '16px',
        'hf-20': '20px',
        'hf-24': '24px',
        'hf-32': '32px',
        'hf-48': '48px',
        'hf-64': '64px',
        "tg-safe-bottom": "var(--tg-viewport-safe-area-inset-bottom, 0px)",
        "tg-safe-top": "var(--tg-viewport-safe-area-inset-top, 0px)",
      },
      boxShadow: {
        'hf-card': '0 2px 8px var(--hf-shadow)',
        'hf-toast': '0 4px 16px var(--hf-shadow)',
        'hf-bottom-nav': '0 -2px 20px var(--hf-shadow)',
        'hf-thumb': '0 1px 4px var(--hf-shadow)',
        'hf-toggle-thumb': '0 1px 4px rgba(0,0,0,0.15)',
      },
    },
  },
  plugins: [],
}
